# Generated by Django 3.2.5 on 2021-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_orm', '0002_wizard_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='house',
            field=models.CharField(choices=[('Gryffindor', 'Gryffindor'), ('Slytherin', 'Slytherin'), ('Ravenclaw', 'Ravenclaw'), ('Hufflepuff', 'Hufflepuff')], max_length=45),
        ),
    ]
