# Generated by Django 3.2.5 on 2021-08-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_orm', '0003_alter_wizard_house'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wizard',
            table='wizards',
        ),
    ]
