# Generated by Django 3.2.5 on 2021-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_orm', '0004_alter_wizard_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
