# Generated by Django 3.2.5 on 2021-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_orm', '0005_alter_wizard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
