# Generated by Django 3.2.7 on 2021-10-11 03:46

from django.db import migrations, models
import django.utils.timezone
import shows_crud.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('network', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', shows_crud.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
    ]
